name: Daily Supabase Backup

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL Client 17
        run: |
          # Adiciona o repositório e a chave de forma silenciosa e não interativa
          sudo apt-get update
          sudo apt-get install -y curl ca-certificates
          curl -sS https://www.postgresql.org | gpg --dearmor | sudo tee /usr/share/keyrings/pgdg.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/pgdg.gpg] http://apt.postgresql.org $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Run backup
        run: |
          CLEAN_URL=$(echo "${{ secrets.SUPABASE_DB_URL }}" | cut -d'?' -f1)
          /usr/lib/postgresql/17/bin/pg_dump "$CLEAN_URL" -F c -f backup.dump

      - name: Save Backup Artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: backup.dump
